# Generated by Django 3.1.2 on 2020-10-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=50)),
                ('cedula', models.IntegerField(default=10)),
                ('direccion', models.CharField(default='N/A', max_length=50)),
                ('telefono', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=50)),
                ('cedula', models.IntegerField(default=10)),
                ('direccion', models.CharField(default='N/A', max_length=50)),
                ('telefono', models.IntegerField(default=10)),
                ('curso', models.CharField(default='N/A', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLibros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Libro', models.IntegerField(default=5)),
                ('nombre_Libro', models.CharField(default='N/A', max_length=100)),
                ('numero_paginas', models.IntegerField(default=5)),
                ('autor', models.CharField(default='N/A', max_length=50)),
                ('nivel_academico', models.CharField(default='N/A', max_length=50)),
            ],
        ),
    ]
