# Generated by Django 3.1.2 on 2020-10-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miedu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrolibros',
            old_name='nombre_Libro',
            new_name='nombre_Libros',
        ),
    ]
